version: '3'
services:
    web:
        container_name: xmas_web
        image: nginx:latest
        restart: always
        volumes:
            - './':/usr/share/nginx/html
        ports:
            - "8008:80"            
        networks:
            - web
        labels:
            - traefik.http.routers.on_vacation.rule=Host(${HOST_NAME})
            - traefik.http.routers.on_vacation.tls=true
            - traefik.http.routers.on_vacation.tls.certresolver=lets-encrypt
            - traefik.http.services.on_vacation.loadbalancer.server.port=80
networks:
  web:
    external: true
